[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E", "F", "I", "UP", "B"]
ignore = []

[tool.ruff.isort]
known-first-party = ["core", "modules", "strategy"]
combine-as-imports = true
